## 动手学深度学习 2.1 自我操作

In [88]:
import torch
import numpy as np

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
x.shape



torch.Size([12])

In [90]:

x.numel()

12

In [91]:
X = x.reshape(3, 4)
Y = torch.reshape(x, [3, 4])
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [92]:
x = torch.randn(3, 4)
x

tensor([[ 0.1465, -0.1095, -0.1842, -0.2369],
        [-0.7632, -0.1212,  1.4304,  0.3763],
        [ 0.6747,  0.9810, -0.9595, -0.2021]])

In [93]:
X = torch.tensor([2,3,4,2])
Y = torch.randn(4)

print(id(Y))
Y = X + Y

print(id(Y))


1942227811712
1942319431280


In [94]:
X = torch.tensor([2,3,4,2])
Y = torch.rand(4)

print(id(Y))
Y += X
print(id(Y))
Y[:] = X + Y
print(id(Y))

1942318859584
1942318859584
1942318859584


In [95]:
a = torch.tensor([[0,1,2],[1,1,2]])
b = torch.tensor([[[0]],[[1]]])
a + b

tensor([[[0, 1, 2],
         [1, 1, 2]],

        [[1, 2, 3],
         [2, 2, 3]]])

In [96]:
a = torch.tensor([4.6])
a, a.item(), float(a), int(a)

(tensor([4.6000]), 4.599999904632568, 4.599999904632568, 4)

In [99]:
c = np.array([1,2,3,4.1])
d = torch.from_numpy(c)
d.requires_grad_(True)

type(c), type(d)

c[1] = 3.1
c, d

(array([1. , 3.1, 3. , 4.1]),
 tensor([1.0000, 3.1000, 3.0000, 4.1000], dtype=torch.float64,
        requires_grad=True))