# 2.3 线性代数

## 2.3.1 标量


In [1]:
import torch

x = torch.tensor(3.9)
y = torch.tensor(4.0)

x + y, x * y, x / y

(tensor(7.9000), tensor(15.6000), tensor(0.9750))

## 2.3.2 向量

In [2]:
x = torch.arange(start=0, end=2, step=0.1)
x

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000])


在数学中，列向量$\mathbf{x}$如下表示：

$
\begin{equation}
\mathbf{x}=\left[\begin{array}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{array}\right]
\end{equation}
$

In [3]:
x[3]

tensor(0.3000)

In [4]:
len(x)

20

In [5]:
x.shape

torch.Size([20])

## 2.3.3 矩阵

In [6]:
A = torch.arange(20).reshape(-1, 4)
print(A.permute(1, 0))
print(A)
print(A.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [7]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [8]:
X = torch.arange(30).reshape(2,3,5)
Y = torch.arange(30).reshape(2,5,3)
torch.bmm(X, Y)

tensor([[[  90,  100,  110],
         [ 240,  275,  310],
         [ 390,  450,  510]],

        [[1815, 1900, 1985],
         [2340, 2450, 2560],
         [2865, 3000, 3135]]])

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
print(B)

A[0,1] = 100


B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [10]:
from transformers import SegformerImageProcessor, SegformerForSemanticSegmentation
from PIL import Image
import requests

feature_extractor = SegformerImageProcessor.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512")
model = SegformerForSemanticSegmentation.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = feature_extractor(images=image, return_tensors="pt")
outputs = model(**inputs)
logits = outputs.logits  # shape (batch_size, num_labels, height/4, width/4)
print(1)

c:\Users\zhang\miniconda3\envs\d2l\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\zhang\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\zhang\miniconda3\envs\d2l\lib\site-packages\transformers\models\segformer\image_processing_segformer.py:99: FutureWarning: The `re

1


In [11]:
from transformers import pipeline

segmenter = pipeline("image-segmentation", model="facebook/detr-resnet-50-panoptic")

Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth" to C:\Users\zhang/.cache\torch\hub\checkpoints\resnet50_a1_0-14fe96d1.pth
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth" to C:\Users\zhang/.cache\torch\hub\checkpoints\resnet50_a1_0-14fe96d1.pth


ValueError: Could not load model facebook/detr-resnet-50-panoptic with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForImageSegmentation'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSemanticSegmentation'>, <class 'transformers.models.detr.modeling_detr.DetrForSegmentation'>).