In [19]:
import torch

a = torch.rand(3, 4, 2)
a

tensor([[[0.1873, 0.7278],
         [0.5534, 0.7286],
         [0.6437, 0.4324],
         [0.2792, 0.4810]],

        [[0.0154, 0.7719],
         [0.6577, 0.2923],
         [0.8942, 0.4666],
         [0.9937, 0.5822]],

        [[0.5403, 0.0350],
         [0.0219, 0.5796],
         [0.6084, 0.3200],
         [0.8908, 0.2576]]])

In [20]:
b = a.transpose(1, 0)
b

tensor([[[0.1873, 0.7278],
         [0.0154, 0.7719],
         [0.5403, 0.0350]],

        [[0.5534, 0.7286],
         [0.6577, 0.2923],
         [0.0219, 0.5796]],

        [[0.6437, 0.4324],
         [0.8942, 0.4666],
         [0.6084, 0.3200]],

        [[0.2792, 0.4810],
         [0.9937, 0.5822],
         [0.8908, 0.2576]]])

In [21]:
c = a.permute(0, 1)
c

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 2

In [ ]:
d = a.permute(1, 0)
d

tensor([[0.1272, 0.9531, 0.8766],
        [0.8190, 0.9699, 0.6580],
        [0.6215, 0.0145, 0.6369],
        [0.1728, 0.3260, 0.6246]])