In [15]:
import torch

a = torch.rand(3, 4, 2)
a

tensor([[0.1272, 0.8190, 0.6215, 0.1728],
        [0.9531, 0.9699, 0.0145, 0.3260],
        [0.8766, 0.6580, 0.6369, 0.6246]])

In [16]:
b = a.transpose(1, 0)
b

tensor([[0.1272, 0.9531, 0.8766],
        [0.8190, 0.9699, 0.6580],
        [0.6215, 0.0145, 0.6369],
        [0.1728, 0.3260, 0.6246]])

In [17]:
c = a.permute(0, 1)
c

tensor([[0.1272, 0.8190, 0.6215, 0.1728],
        [0.9531, 0.9699, 0.0145, 0.3260],
        [0.8766, 0.6580, 0.6369, 0.6246]])

In [18]:
d = a.permute(1, 0)
d

tensor([[0.1272, 0.9531, 0.8766],
        [0.8190, 0.9699, 0.6580],
        [0.6215, 0.0145, 0.6369],
        [0.1728, 0.3260, 0.6246]])